### PR TITLE
Newbie ed 2019

### PR DESCRIPTION
**Pull request by CreativePenguin**

### CODE REVIEW

**Comment by CreativePenguin** [comment]
I tried squashing my commits, but I don't know how it went.

**Comment by justinkim** [comment]
@CreativePenguin Did you want to squash everything into one commit?

**Comment by CreativePenguin** [comment]
@justinkim Well, I wanted to do it just so I would know how. Are you supposed to do it by doing `git rebase -i master`, or is selecting the `squash and merge` option under `merge pull request` all you need to do?

**Comment by CreativePenguin** [comment]
Sorry, I wanted to restore the branch because I wanted to make sure @Kevin16777216 read it. I wrote a bit about the newbie ed game that he primarily led, and I wanted to make sure that they were accurate.

**Pull request merged**
